### PR TITLE
Fix for missing validation of indexer input

### PR DESCRIPTION
**Pull request by skovhus**
This fixes https://github.com/codemix/flow-runtime/issues/186

It seems the code tried to handle this, but in JavaScript `typeof [] === object`. 

Here I'm introducing https://lodash.com/docs/4.17.4#isPlainObject which is a very small utility that does correctly checks if something is a plain object, that is, an object created by the Object constructor or one with a `Prototype` of `null`.

### CODE REVIEW

**Comment by jedwards1211** [comment]
I'm not sure we want to check if the input is a plain object, because `declare class` types support an indexable signature, and flow maintainers want to eventually support it on actual `class` declarations too: https://github.com/facebook/flow/issues/1323

Any objections to just using `input instanceof Object && !Array.isArray(input)`?

**Comment by skovhus** [comment]
> Any objections to just using input instanceof Object && !Array.isArray(input)?

Sounds good to me. I'll just add it on this branch, ok? : )

**Comment by jedwards1211** [comment]
Sounds good!

**Comment by skovhus** [comment]
@jedwards1211 should be there now. : )

**Comment by jedwards1211** [comment]
Thanks!

**Pull request merged**
