### PR TITLE
fix(babel-plugin-flow-runtime): fix duplicate declaration bug

### LINKED ISSUE #201: Function argument destructuring and default value generates "syntax" error
This is a:

 - [x] Bug Report
 - [ ] Feature Request
 - [ ] Question
 - [ ] Other

Which concerns:

 - [x] flow-runtime
 - [x] babel-plugin-flow-runtime
 - [ ] flow-runtime-validators
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

---

### What is the current behaviour?

```js
const defaultTrx = 'abc'
class Test {
  static async getLastUpdateTimestamp ({ trx }: { trx: any } = { trx: defaultTrx }) { /* do nothing */ }
}
```
* flow check itself (`flow check --strip-root`) does not complain about this
* this function works as expected on runtime

However when I enable `babel-plugin-flow-runtime` and then I start my program I get following error:
```
Duplicate declaration "trx"
```

.babelrc.js:

```js
module.exports = {
  presets: [
    '@babel/flow',
    [ '@babel/env', {
      targets: {
        node: 'current'
      }
    }]
  ],
  plugins: [
    '@babel/proposal-class-properties',
    '@babel/proposal-object-rest-spread',
    '@babel/proposal-export-namespace',
    '@babel/proposal-decorators',
    ['root-import', {
      rootPathPrefix: '@',
      rootPathSuffix: 'src'
    }],
    ['flow-runtime', {
      assert: false,
      annotate: false
    }]
  ],
  env: {
    test: {
      plugins: ['istanbul']
    }
  }
}
```

Without flow-runtime plugin in .babelrc.js it works during runtime (no syntax errors) and also flow does not complain about it during flow check.

---

### What is the expected behaviour?
It should not throw error, this is correct syntax and it's supported by flow.

---

### Which package versions are you using?
```json
"flow-runtime": "^0.17.0",
"babel-plugin-flow-runtime": "^0.17.0",
"@babel/preset-flow": "^7.0.0-beta.32"
```

### PR DESCRIPTION
**Pull request by jedwards1211**
fix #201

### CODE REVIEW

**Comment by linonetwo** [comment]
Is build process still good? It says `Requires Babel "^7.0.0-0", but was loaded with "6.26.3".`

**Comment by jedwards1211** [comment]
It's kind of up in the air, there's a lot of complexity no one has found time to wrestle with yet 😅

**Comment by jedwards1211** [comment]
@linonetwo nevertheless I plan to get this fix released tomorrow

**Comment by jedwards1211** [comment]
this is released in v0.19.0!

**Pull request closed without merging**
