### PR TITLE
feat(pragma): add optInOnly option

### LINKED ISSUE #153: Feature Request: option to ignore all files by default
This is a:

 - [ ] Bug Report
 - [x] Feature Request
 - [ ] Question
 - [ ] Other

Which concerns:

 - [ ] flow-runtime
 - [x] babel-plugin-flow-runtime
 - [ ] flow-runtime-validators
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

I only want to use `babel-plugin-flow-runtime` to `reify` various types, but I don't want to convert any unreified types to validators.  I'm thinking the easiest approach would be to make `babel-plugin-flow-runtime` ignore all files by default, and then put a `/* flow-runtime convert */` pragma at the top of files where I want to `reify` something.  `/* flow-runtime convert */` would mean re-enable `babel-plugin-flow-runtime` with `{assert: false, annotate: false}` (i.e. just convert type aliases and inline reified types to validators).

There is one pitfall: if I try to `reify` a type imported from another file that's ignored by `babel-plugin-flow-runtime`, it would fail at runtime without any compile-time warnings.

### PR DESCRIPTION
**Pull request by jedwards1211**
fix #153 

with this PR, if you put `"optInOnly": true` in the plugin options, it will ignore all files that don't have a `/* @flow-runtime */` annotation.

**Important note**: `/* @flow-runtime */` with no extra options still defaults to `assert, annotate`.  So if you have `"assert": false, "annotate": false, "optInOnly": true` in your plugin options and want to opt-in for a file without turning on `"assert" or "annotate"`, you have to put an annotation like `/* @flow-runtime enable */` or `/* @flow-runtime convert */`.  Any nonsense option will opt in without different options than the plugin.  Personally, I wish that `/* @flow-runtime */` would not turn on `assert` and `annotate` if they're disabled in the plugin options.

### CODE REVIEW

**Comment by jedwards1211** [comment]
@phpnode this should be ready to go, I merged in master

**Comment by jedwards1211** [comment]
I figured this would be a pretty simple alternative to getting `generateReifiedOnly` fully working

**Comment by jedwards1211** [comment]
@phpnode do you want to eventually merge this or do you not like the idea?

**Comment by phpnode** [comment]
@jedwards1211 sorry for the delay, yes this is a practical alternative, thanks!

**Comment by Ashoat** [comment]
Is there a way to use this? Looks like a release with this PR hasn't been cut yet, and there's no easy way to npm install a folder within a git repo...

**Comment by jedwards1211** [comment]
@Ashoat thanks for pinging us, we need to release this.
@phpnode I know you're pretty busy these days, I'd be happy to publish a new release if you're willing to give me permission to do so on npm.

**Pull request merged**
