### PR TITLE
WIP: add option to only generate validators for reified types

### LINKED ISSUE #151: Feature Request: option to disable conversion to validators except for reified types
This is a:

 - [ ] Bug Report
 - [x] Feature Request
 - [ ] Question
 - [ ] Other

Which concerns:

 - [ ] flow-runtime
 - [x] babel-plugin-flow-runtime
 - [ ] flow-runtime-validators
 - [ ] flow-runtime-mobx
 - [ ] flow-config-parser
 - [ ] The documentation website

I only want to use `babel-plugin-flow-runtime` to `reify` type defs and explicitly validate JSON with them.  But even if I use `["flow-runtime", {"assert": false, "annotate": false}]` in my `.babelrc`, it still converts all type aliases to validators.  Since I'm not planning to perform runtime assertions for most of my type annotations, it's a waste of resources to convert types that I never `reify` to validators.

Implementing this would be complex, considering that all types that any given `reified` type depends on must also be converted to validators, so maybe we should close this in favor of #153.

### PR DESCRIPTION
**Pull request by jedwards1211**
fix #151 

If you put `"generateReifiedOnly": true` in the options, then `type User = ...` will only be converted into a runtime validator if there's a `(reify: User)` or `(reify: Type<User>)` statement somewhere in the file.

If you guys want me to call this option something else let me know and I'll change it.

**TODO**: if `User` depends on an `Address` type and only `User` is reified, `Address` also needs to be converted into a validator.  Right now this PR doesn't track the dependencies between types necessary to do that.

### How it works
I added a `TypeCastExpression` visitor to `preTransformVisitors` that looks for `reify` casts, and if found, looks up the entity for the type and marks it as `reified: true`.

The `TypeAlias` converter then does a no-op if `generateReifiedOnly` is `true` and the entity isn't `reified`:
```js
  const entity = context.getEntity(name, path);
  if (context.shouldGenerateReifiedOnly && (!entity || !entity.reified)) {
    return path.node;
  }
```

### Example Input
```js
/* @flow */

import t, {reify} from 'flow-runtime';
import type {Type} from 'flow-runtime';

type User = {
  username: string;
  email: string;
};

const UserType = (reify: User);

type Address = {
  street: string;
  city: string;
  state: string;
  zip: string;
}

const AddressType = (reify: Type<Address>);

type Unreified = {
  foo: number;
}
```

### Example Output
Notice that `Unreified` isn't converted into a validator:

```js
'use strict';

var _flowRuntime = require('flow-runtime');

var _flowRuntime2 = _interopRequireDefault(_flowRuntime);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var Type = _flowRuntime2.default.tdz(function () {
  return _flowRuntime.Type;
});

var User = _flowRuntime2.default.type('User', _flowRuntime2.default.object(_flowRuntime2.default.property('username', _flowRuntime2.default.string()), _flowRuntime2.default.property('email', _flowRuntime2.default.string())));

var UserType = User;

var Address = _flowRuntime2.default.type('Address', _flowRuntime2.default.object(_flowRuntime2.default.property('street', _flowRuntime2.default.string()), _flowRuntime2.default.property('city', _flowRuntime2.default.string()), _flowRuntime2.default.property('state', _flowRuntime2.default.string()), _flowRuntime2.default.property('zip', _flowRuntime2.default.string())));

var AddressType = Address;
```

### CODE REVIEW

**Comment by jedwards1211** [comment]
Just pushed tests

**Comment by phpnode** [comment]
@jedwards1211 thanks for this and sorry for the delay!

**Comment by jedwards1211** [comment]
@phpnode whoa, thanks but I didn't really think this was ready to be merged, that's why I marked it WIP.  As I mentioned above, if `User` depends on an `Address` type and only `User` is reified, `Address` also needs to be converted into a validator. Right now this PR doesn't track the dependencies between types necessary to do that.

**Comment by phpnode** [comment]
@jedwards1211 this is looking good so far, I merged because (I think) I have an easy fix for the dependencies, I'm working on the lib for the next couple of days and so might churn a few things - it's easier to get this in now rather than syncing it later :)

**Comment by jedwards1211** [comment]
@phpnode oh, cool! looking forward to it :)

**Comment by jedwards1211** [comment]
@phpnode do you think `convertReifiedOnly` would be a better name for the option?

**Pull request merged**
