### PR TITLE
Add moduleName to options of babel-plugin

### PR DESCRIPTION
**Pull request by k15a**
This option is useful for a fork or when you use a monorepo and node is not resolving the path correctly.

### CODE REVIEW

**Comment by jedwards1211** [comment]
@k15a I think `moduleName` is too vague, how about we rename this to `flowRuntimePath`?

**Comment by k15a** [comment]
@jedwards1211 I took the name from babel-plugin-transform-runtime. I've changed it to flowRuntimePath.

**Comment by jedwards1211** [comment]
@k15a cool, thanks!  Would you mind adding a test for this?

**Comment by phpnode** [comment]
Sorry to pile on the bikeshed, but if this is setting something called `libraryName` then let's call the option `libraryName`

**Comment by k15a** [comment]
@jedwards1211 @phpnode I've added tests and changed the name of the option to libraryName. Please let me know if I can do anything else to get this merged and released.

**Comment by phpnode** [comment]
@k15a thanks for this! I'll do a release within the next few hours

**Comment by k15a** [comment]
Thank you very much.

**Pull request merged**
